% L3 Stage B -- judge. Registration: test_script/scratch/l3_stageB_prereg.txt
% STATUS: ACTIVE (scratch, L3 instrument) | PURPOSE: paired per-seed comparison
%   of the predict_quad arms B1 ('mid') / B2 ('trap') against the production
%   baseline B0 (l2_base_100.mat, left rule) on the registered readouts; the
%   H1/H2/H3 branch; two figure pages | EXPIRES: Stage B closes.
% Inputs: test_results/l3_stageB/l3_{left,mid,trap}_100.mat (left = B0, regenerated by
% l3_stageB_run_arms.m because l2_loo/l2_base_100.mat predates the 1a70599 production change).
% Seeds are the only resampling unit (l0_jackknife_se). Reports raw numbers and the
% registered branch only; proposes nothing.
cd('/Users/kevin/code/MotionControl_Simu-motion-test');
root = pwd;
addpath(fullfile(root, 'test_script', 'scratch'));
B0_FILE = fullfile(root, 'test_results', 'l3_stageB', 'l3_left_100.mat');   % B0 regenerated on the current production (l2_base_100 predates 1a70599)
IN_DIR  = fullfile(root, 'test_results', 'l3_stageB');
FIG_DIR = IN_DIR;
AX = 3;                                   % z, wall-normal
ACF_LAGS = 1:5;
ACF_BAND = 0.06;
HOLD_REG = [3.8, 4.8];                    % registered trough-hold window

% ---------------------------------------------------------------- load
A = struct();
A.B0 = local_load(B0_FILE);
% pre-1a70599 L2 baseline, loaded ONLY for the production-change delta (lead request 08-30); never a pair target for B1/B2
L2_FILE = fullfile(root, 'test_results', 'l2_loo', 'l2_base_100.mat');
if exist(L2_FILE, 'file'); A.L2base = local_load(L2_FILE); end
for nm = {'mid', 'trap'}
    fn = fullfile(IN_DIR, sprintf('l3_%s_100.mat', nm{1}));
    if ~exist(fn, 'file'); fprintf('[skip] %s not found\n', fn); continue; end
    A.(nm{1}) = local_load(fn);
end
have = fieldnames(A);
B = A.B0; ns = B.ns; t = B.t; seeds = B.seeds;
w = B.windows;
m_desc = t >= w.descent(1) & t <= w.descent(2);
m_osc  = t >  w.osc(1)     & t <= w.osc(2);
m_hold = t >  w.hold(1);
m_hreg = t >= HOLD_REG(1) & t <= HOLD_REG(2);
fprintf('windows (driver): descent [%.2f,%.2f] osc (%.2f,%.2f] hold (%.2f,end=%.2f]; registered hold [%.1f,%.1f] -> %d vs %d samples\n', ...
        w.descent, w.osc, w.hold(1), t(end), HOLD_REG, sum(m_hold), sum(m_hreg));
for i = 1:numel(have)
    r = A.(have{i});
    assert(isequal(r.seeds(:), seeds(:)) && r.ns == ns && numel(r.t) == numel(t), 'l3_stageB_judge:pairing', 'arm %s not paired with B0', have{i});
    if isfield(r, 'predict_quad'); pq = r.predict_quad; elseif strcmp(have{i}, 'L2base'); pq = 'left (pre-1a70599 L2 base, 08-25)'; else; pq = 'left (B0)'; end
    fprintf('  arm %-4s : predict_quad = %s ; override %s\n', have{i}, pq, jsonencode(r.override));
end

% ---------------------------------------------------------------- per-seed stats
S = struct();
for i = 1:numel(have)
    r = A.(have{i});
    q = struct();
    at = squeeze(r.a_true_norm(:, AX, :));   ah = squeeze(r.a_bar_hat(:, AX, :));
    q.a_T      = mean(at(m_hold, :), 1).';
    q.bias_pct = (100 * mean(ah(m_hold, :) - at(m_hold, :), 1) ./ q.a_T.').';
    q.bias_abs = mean(ah(m_hold, :) - at(m_hold, :), 1).';           % [-] normalised, for honesty
    q.bias_pct_reg = (100 * mean(ah(m_hreg, :) - at(m_hreg, :), 1) ./ mean(at(m_hreg, :), 1)).';
    q.hold_mean_pct_drv = r.metrics.rows(:, 3);
    q.desc_pk_drv = r.metrics.rows(:, 1);
    q.osc_rms_drv = r.metrics.rows(:, 2);
    q.desc_pk_z   = (100 * max(ah(m_desc, :) - at(m_desc, :), [], 1) ./ q.a_T.').';   % own peak, % of a_T
    q.osc_rms_z   = (100 * sqrt(mean((ah(m_osc, :) - at(m_osc, :)).^2, 1)) ./ q.a_T.').';
    q.bhat_end    = squeeze(r.b_hat(end, AX, :));
    % innov2 mean per window (gate-open only) and |K_a_y2| hold
    i2 = squeeze(r.innov_y2(:, AX, :)); g = squeeze(r.gate(:, AX, :));
    ka2 = squeeze(r.K_a_y2(:, AX, :)); ka1 = squeeze(r.K_a_y1(:, AX, :));
    q.innov2_desc = nan(ns, 1); q.innov2_osc = nan(ns, 1); q.innov2_hold = nan(ns, 1);
    q.Ka2_hold = nan(ns, 1); q.Ka1_hold = mean(abs(ka1(m_hold, :)), 1).';
    q.n_open_hold = zeros(ns, 1);
    for s = 1:ns
        md = m_desc & ~g(:, s); mo = m_osc & ~g(:, s); mh = m_hold & ~g(:, s);
        q.n_open_hold(s) = sum(mh);
        if sum(md) > 10; q.innov2_desc(s) = mean(i2(md, s)); end
        if sum(mo) > 10; q.innov2_osc(s)  = mean(i2(mo, s)); end
        if sum(mh) > 10; q.innov2_hold(s) = mean(i2(mh, s)); q.Ka2_hold(s) = mean(abs(ka2(mh, s))); end
    end
    % innov1 acf in hold
    i1 = squeeze(r.innov_y1(:, AX, :));
    q.acf_hold = zeros(ns, numel(ACF_LAGS));
    for s = 1:ns; q.acf_hold(s, :) = local_acf(i1(m_hold, s), ACF_LAGS); end
    % P44 honesty: per-seed sqrt(P44) in hold, and |bias|/sqrt(P44)
    Pa = squeeze(r.P_a(:, AX, :));                        % variance, normalised
    q.sqrtP_hold = mean(sqrt(max(Pa(m_hold, :), 0)), 1).';
    q.abs_err_over_sqrtP = abs(q.bias_abs) ./ q.sqrtP_hold;
    % clamp / gate census (lower bounds)
    cc = r.K;
    a_floor = local_gfd(cc, 'a_bar_floor', 0.05);  a_ceil = local_gfd(cc, 'a_bar_ceil', 1 - 1e-4);
    q.n_afloor = sum(ah == a_floor, 1).'; q.n_aceil = sum(ah == a_ceil, 1).';
    q.n_gate_hold = sum(g(m_hold, :), 1).';
    q.n_nan = sum(~isfinite(ah), 1).';
    S.(have{i}) = q;
end

% ---------------------------------------------------------------- baseline block
rep = @(name, x) fprintf('  %-36s mean %+.5g  sd %.4g  SEM %.4g  (n=%d)\n', name, mean(x, 'omitnan'), ...
                         std(x, 0, 'omitnan'), local_sem(x), sum(isfinite(x)));
fprintf('\n================ B0 (arm best, production, left rule) ================\n');
b = S.B0;
rep('a_T (trough truth, norm)', b.a_T);
rep('hold bias_pct (z, % of a_T)', b.bias_pct);
rep('hold bias_pct registered [3.8,4.8]', b.bias_pct_reg);
rep('driver hold mean %', b.hold_mean_pct_drv);
rep('driver desc peak %', b.desc_pk_drv);
rep('desc peak z (% of a_T)', b.desc_pk_z);
rep('driver osc RMS %', b.osc_rms_drv);
rep('osc RMS z (% of a_T)', b.osc_rms_z);
rep('b_hat end', b.bhat_end);
rep('innov2 mean desc (gate-open)', b.innov2_desc);
rep('innov2 mean osc (gate-open)', b.innov2_osc);
rep('innov2 mean hold (gate-open)', b.innov2_hold);
rep('|K_a_y1| hold', b.Ka1_hold);
rep('|K_a_y2| hold (gate-open)', b.Ka2_hold);
rep('sqrt(P44) hold (norm)', b.sqrtP_hold);
rep('|bias|/sqrt(P44) hold (per seed)', b.abs_err_over_sqrtP);
for L = 1:numel(ACF_LAGS); rep(sprintf('innov1 acf lag%d (hold)', ACF_LAGS(L)), b.acf_hold(:, L)); end
[hs, hs_se] = local_sd_jack(b.bias_pct);
fprintf('  %-36s %.4g  (jackknife SE %.4g)\n', 'seed sd of hold bias [pp]', hs, hs_se);
[hn, hn_se] = local_ratio_jack(b.bias_abs, b.sqrtP_hold);
fprintf('  %-36s %.4g  (jackknife SE %.4g)   [spread of hold bias over seeds / mean sqrt(P44)]\n', 'P44 honesty spread/sqrt(P)', hn, hn_se);

% ---------------------------------------------------------------- paired tables
PAIRS = {'mid', 'B0', 'B1 - B0 (mid - left)'; 'trap', 'B0', 'B2 - B0 (trap - left)'; 'mid', 'trap', 'B1 - B2 (mid - trap)'; ...
         'B0', 'L2base', 'PRODUCTION CHANGE: fresh left (1a70599) - l2_base_100 (pre-1a70599), NOT a Stage B arm'};
V = struct();
for pI = 1:size(PAIRS, 1)
    xa = PAIRS{pI, 1}; xb = PAIRS{pI, 2};
    if ~isfield(S, xa) || ~isfield(S, xb); continue; end
    q = S.(xa); b = S.(xb);
    key = sprintf('%s_vs_%s', xa, xb);
    fprintf('\n================ %s (paired per seed, n=%d) ================\n', PAIRS{pI, 3}, ns);
    fprintf('  %-28s %-38s | %-38s | diff\n', 'readout', ['A=' xa], ['B=' xb]);
    P = struct();
    P.bias_pct  = local_pair(q.bias_pct, b.bias_pct, 'hold bias_pct [pp of a_T]');
    P.bias_reg  = local_pair(q.bias_pct_reg, b.bias_pct_reg, 'hold bias_pct [3.8,4.8] [pp]');
    P.hold_drv  = local_pair(q.hold_mean_pct_drv, b.hold_mean_pct_drv, 'driver hold mean %');
    P.desc_drv  = local_pair(q.desc_pk_drv, b.desc_pk_drv, 'driver desc peak %');
    P.desc_z    = local_pair(q.desc_pk_z, b.desc_pk_z, 'desc peak z [pp of a_T]');
    P.osc_drv   = local_pair(q.osc_rms_drv, b.osc_rms_drv, 'driver osc RMS %');
    P.osc_z     = local_pair(q.osc_rms_z, b.osc_rms_z, 'osc RMS z [pp of a_T]');
    P.bhat_end  = local_pair(q.bhat_end, b.bhat_end, 'b_hat end');
    P.innov2_desc = local_pair(q.innov2_desc, b.innov2_desc, 'innov2 mean desc');
    P.innov2_osc  = local_pair(q.innov2_osc, b.innov2_osc, 'innov2 mean osc');
    P.innov2_hold = local_pair(q.innov2_hold, b.innov2_hold, 'innov2 mean hold');
    P.Ka1       = local_pair(q.Ka1_hold, b.Ka1_hold, '|K_a_y1| hold');
    P.Ka2       = local_pair(q.Ka2_hold, b.Ka2_hold, '|K_a_y2| hold');
    P.sqrtP     = local_pair(q.sqrtP_hold, b.sqrtP_hold, 'sqrt(P44) hold');
    P.honesty_ps = local_pair(q.abs_err_over_sqrtP, b.abs_err_over_sqrtP, '|bias|/sqrt(P44) per seed');
    for L = 1:numel(ACF_LAGS)
        P.(sprintf('acf%d', L)) = local_pair(q.acf_hold(:, L), b.acf_hold(:, L), sprintf('innov1 acf lag%d hold', ACF_LAGS(L)));
    end
    % seed sd of hold bias (not a mean: jackknife on the sd itself and on the sd difference)
    [sa, sa_se] = local_sd_jack(q.bias_pct); [sb, sb_se] = local_sd_jack(b.bias_pct);
    [dsd, dsd_se] = local_sd_diff_jack(q.bias_pct, b.bias_pct);
    fprintf('  %-28s A %.4g (SE %.4g) | B %.4g (SE %.4g) | diff %+.4g SE %.4g t=%+.2f\n', ...
            'seed sd of hold bias [pp]', sa, sa_se, sb, sb_se, dsd, dsd_se, dsd / dsd_se);
    P.sd_bias = struct('a', sa, 'b', sb, 'mu', dsd, 'se', dsd_se, 't', dsd / dsd_se);
    [ha, ha_se] = local_ratio_jack(q.bias_abs, q.sqrtP_hold); [hb, hb_se] = local_ratio_jack(b.bias_abs, b.sqrtP_hold);
    [dh, dh_se] = local_ratio_diff_jack(q.bias_abs, q.sqrtP_hold, b.bias_abs, b.sqrtP_hold);
    fprintf('  %-28s A %.4g (SE %.4g) | B %.4g (SE %.4g) | diff %+.4g SE %.4g t=%+.2f\n', ...
            'P44 honesty spread/sqrt(P)', ha, ha_se, hb, hb_se, dh, dh_se, dh / dh_se);
    P.honesty = struct('a', ha, 'b', hb, 'mu', dh, 'se', dh_se, 't', dh / dh_se);
    % acf band check (registered: must stay within +-0.06 on the arm)
    acf_mu = mean(q.acf_hold, 1);
    fprintf('  innov1 acf hold, arm %s, lags 1-5 mean: %s  -> within +-%.2f: %s\n', xa, mat2str(acf_mu, 3), ACF_BAND, ...
            local_yesno(all(abs(acf_mu) <= ACF_BAND)));
    % census
    fprintf('  census (z): a==floor %s | a==ceil %s | gate hold %s | NaN %d   [arm %s]\n', ...
            local_cnt(q.n_afloor), local_cnt(q.n_aceil), local_cnt(q.n_gate_hold), sum(q.n_nan), xa);
    fprintf('  sign census of paired hold bias diff: negative %d / zero %d / positive %d of %d seeds\n', ...
            sum(q.bias_pct - b.bias_pct < 0), sum(q.bias_pct - b.bias_pct == 0), sum(q.bias_pct - b.bias_pct > 0), ns);
    V.(key) = P;
end

% ---------------------------------------------------------------- registered branch
fprintf('\n================ REGISTERED BRANCH (z, trough-hold bias, pp of a_T, paired vs B0) ================\n');
fprintf('  H1: B1-B0 = -9 +- 3 pp AND B2 within 0.5 pp of B1 | H2: |B1-B0| < 4 or > 15 | H3: B1-B0 > 0 -> stop\n');
for nm = {'mid', 'trap'}
    key = sprintf('%s_vs_B0', nm{1});
    if ~isfield(V, key); continue; end
    P = V.(key).bias_pct;
    br = local_branch(P.mu);
    fprintf('  arm %-4s: diff %+.3f pp (sd %.3f SEM %.3f t=%+.2f) -> %s\n', nm{1}, P.mu, P.sd, P.se, P.t, br);
end
if isfield(V, 'mid_vs_trap')
    P = V.mid_vs_trap.bias_pct;
    fprintf('  B1 vs B2: diff %+.3f pp (sd %.3f SEM %.3f t=%+.2f) -> |B1-B2| %s 0.5 pp (H1 second clause %s)\n', ...
            P.mu, P.sd, P.se, P.t, local_lt(abs(P.mu), 0.5), local_yesno(abs(P.mu) < 0.5));
end
if isfield(V, 'mid_vs_B0')
    fprintf('  H3 sign clause (B1-B0 must be negative): mean %+.3f -> %s\n', V.mid_vs_B0.bias_pct.mu, local_yesno(V.mid_vs_B0.bias_pct.mu < 0));
end

% ---------------------------------------------------------------- figures
close all;
i7 = find(seeds == 7, 1);
for nm = {'mid', 'trap'}
    if ~isfield(A, nm{1}); continue; end   % L2base is never plotted
    fig = figure('Position', [50 50 1500 1200], 'Color', 'w');
    arms2 = {'B0', nm{1}}; lab2 = {'B0: left (production)', sprintf('B%d: %s', 1 + strcmp(nm{1}, 'trap'), nm{1})};
    hx = gobjects(3, 2);
    for c = 1:2
        r = A.(arms2{c});
        at = squeeze(r.a_true_norm(:, AX, :)); ah = squeeze(r.a_bar_hat(:, AX, :));
        % row 1: a_bar_hat vs a_true (z), seed 7 + 100-seed mean +- sd
        hx(1, c) = subplot(3, 2, c); hold on; box on;
        mu_h = mean(ah, 2); sd_h = std(ah, 0, 2);
        fill([t; flipud(t)], [mu_h - sd_h; flipud(mu_h + sd_h)], [0.6 0.75 1], 'EdgeColor', 'none', 'FaceAlpha', 0.5);
        plot(t, mean(at, 2), 'r-', 'LineWidth', 1.5);
        plot(t, mu_h, 'b-', 'LineWidth', 1.5);
        plot(t, at(:, i7), 'r:', 'LineWidth', 0.8);
        plot(t, ah(:, i7), 'b:', 'LineWidth', 0.8);
        xline(w.hold(1), 'k--');
        xlabel('t [s]'); ylabel('a\_bar (z) [-]');
        legend({'estimate mean \pm sd (100 seeds)', 'true mean', 'estimate mean', 'true seed 7', 'estimate seed 7', 'hold start'}, ...
               'Location', 'northoutside', 'Orientation', 'horizontal', 'FontSize', 8);
        text(0.02, 0.95, lab2{c}, 'Units', 'normalized', 'FontSize', 10, 'Interpreter', 'none');
        xlim([t(1) t(end)]);
        % row 3: innov1 acf bars hold
        q = S.(arms2{c});
        hx(3, c) = subplot(3, 2, 4 + c); hold on; box on;
        mu_a = mean(q.acf_hold, 1); se_a = zeros(size(mu_a));
        for L = 1:numel(ACF_LAGS); se_a(L) = local_sem(q.acf_hold(:, L)); end
        bar(ACF_LAGS, mu_a, 0.6, 'FaceColor', [0.3 0.5 0.9]);
        errorbar(ACF_LAGS, mu_a, se_a, 'k.', 'LineWidth', 1);
        yline(ACF_BAND, 'k--'); yline(-ACF_BAND, 'k--');
        xlabel('lag [steps]'); ylabel('innov_{y1} acf, hold (z)');
        legend({'mean over 100 seeds', 'SEM', '\pm0.06'}, 'Location', 'northoutside', 'Orientation', 'horizontal', 'FontSize', 8);
        xlim([0.5 numel(ACF_LAGS) + 0.5]);
        text(0.02, 0.95, lab2{c}, 'Units', 'normalized', 'FontSize', 10, 'Interpreter', 'none');
    end
    % row 2 left: paired per-seed hold bias scatter B0 vs Bk with the diagonal
    q = S.(nm{1}); b = S.B0;
    hx(2, 1) = subplot(3, 2, 3); hold on; box on;
    lim = [min([q.bias_pct; b.bias_pct]) - 2, max([q.bias_pct; b.bias_pct]) + 2];
    plot(lim, lim, 'k--');
    scatter(b.bias_pct, q.bias_pct, 18, [0.2 0.4 0.9], 'filled');
    scatter(b.bias_pct(i7), q.bias_pct(i7), 60, 'r', 'LineWidth', 1.2);
    xlabel('B0 hold bias [% of a_T]'); ylabel(sprintf('%s hold bias [%% of a_T]', lab2{2}));
    legend({'diagonal', 'seed', 'seed 7'}, 'Location', 'northoutside', 'Orientation', 'horizontal', 'FontSize', 8);
    xlim(lim); ylim(lim); axis square;
    % row 2 right: paired diff per seed, sorted, with mean +- SEM
    hx(2, 2) = subplot(3, 2, 4); hold on; box on;
    d = q.bias_pct - b.bias_pct; [ds, ord] = sort(d);
    [mu_d, se_d] = l0_jackknife_se(d);
    bar(1:ns, ds, 0.8, 'FaceColor', [0.3 0.5 0.9], 'EdgeColor', 'none');
    j7 = find(ord == i7, 1); bar(j7, ds(j7), 0.8, 'FaceColor', 'r', 'EdgeColor', 'none');
    yline(0, 'k-'); yline(mu_d, 'b-', 'LineWidth', 1.2); yline(mu_d - se_d, 'b:'); yline(mu_d + se_d, 'b:');
    xlabel('seed (sorted by paired diff)'); ylabel('paired hold bias diff [pp of a_T]');
    legend({'seed', 'seed 7', 'zero', 'mean', 'mean \pm SEM'}, 'Location', 'northoutside', 'Orientation', 'horizontal', 'FontSize', 8);
    xlim([0 ns + 1]);
    linkaxes(hx(1, :), 'y'); linkaxes(hx(3, :), 'y');
    out_png = fullfile(FIG_DIR, sprintf('l3_stageB_%s.png', nm{1}));
    exportgraphics(fig, out_png, 'Resolution', 150);
    fprintf('figure: %s\n', out_png);
end
save(fullfile(IN_DIR, 'l3_stageB_judge_stats.mat'), 'S', 'V', 'seeds', 'HOLD_REG', 'ACF_LAGS');
fprintf('\nL3 STAGE B JUDGE DONE\n');

%% ================= local helpers =================
function r = local_load(fn)
    L = load(fn);
    r = l0_load_formC_run(fn, struct('seeds', L.seeds, 'verbose', true));
    nd = r.meta.init_rows_dropped;
    extra = {'K_b_y1', 'K_b_y1_out', 1; 'K_b_y2', 'K_b_y2_out', 1; 'h_bar_d', 'h_bar_d_out', 1; ...
             'h_bar_true', 'h_bar_true_out', 1; 'a_hat', 'a_hat_out', 1; ...
             'P_b', 'P_b_out', 'sq'; 'P_a', 'P_a_out', 'sq_anom'};
    for i = 1:size(extra, 1)
        if ~isfield(L, extra{i, 2}); continue; end
        X = double(L.(extra{i, 2}));
        if ischar(extra{i, 3})
            switch extra{i, 3}
                case 'sq';      X = X.^2;
                case 'sq_anom'; X = (X / L.a_nom).^2;
            end
        end
        r.(extra{i, 1}) = X(1 + nd:end, :, :);
    end
    r.ns = size(r.a_true_norm, 3); r.seeds = L.seeds; r.K = L.K; r.a_nom = L.a_nom;
    r.metrics = L.metrics; r.windows = L.windows; r.arm = L.arm; r.override = L.override;
    if isfield(L, 'predict_quad'); r.predict_quad = L.predict_quad; end
    assert(r.ns == numel(L.seeds), 'seed count mismatch');
end

function v = local_gfd(s, f, d)
    if isfield(s, f); v = s.(f); else; v = d; end
end

function a = local_acf(x, lags)
    x = x(:); x = x - mean(x); den = sum(x.^2);
    a = zeros(1, numel(lags));
    for i = 1:numel(lags)
        L = lags(i);
        a(i) = sum(x(1:end-L) .* x(1+L:end)) / den;
    end
end

function se = local_sem(x)
    x = x(:); x = x(isfinite(x));
    if numel(x) < 2; se = NaN; return; end
    [~, se] = l0_jackknife_se(x);
end

function P = local_pair(xa, xb, name)
    d = xa - xb;
    [mu, se] = l0_jackknife_se(d);
    P = struct('mu', mu, 'se', se, 'sd', std(d, 0, 'omitnan'), 't', mu / se, 'n', sum(isfinite(d)), ...
               'a_mu', mean(xa, 'omitnan'), 'a_sd', std(xa, 0, 'omitnan'), 'a_se', local_sem(xa), ...
               'b_mu', mean(xb, 'omitnan'), 'b_sd', std(xb, 0, 'omitnan'), 'b_se', local_sem(xb));
    fprintf('  %-28s A %+.5g (sd %.4g SEM %.4g) | B %+.5g (sd %.4g SEM %.4g) | diff %+.5g sd %.4g SEM %.4g t=%+.2f (n=%d)\n', ...
            name, P.a_mu, P.a_sd, P.a_se, P.b_mu, P.b_sd, P.b_se, P.mu, P.sd, P.se, P.t, P.n);
end

function [s, se] = local_sd_jack(x)
    x = x(isfinite(x)); n = numel(x);
    s = std(x);
    th = zeros(n, 1);
    for i = 1:n; y = x; y(i) = []; th(i) = std(y); end
    se = sqrt((n - 1) / n * sum((th - mean(th)).^2));
end

function [d, se] = local_sd_diff_jack(xa, xb)
    ok = isfinite(xa) & isfinite(xb); xa = xa(ok); xb = xb(ok); n = numel(xa);
    d = std(xa) - std(xb);
    th = zeros(n, 1);
    for i = 1:n; ya = xa; yb = xb; ya(i) = []; yb(i) = []; th(i) = std(ya) - std(yb); end
    se = sqrt((n - 1) / n * sum((th - mean(th)).^2));
end

function [h, se] = local_ratio_jack(err, sp)
    ok = isfinite(err) & isfinite(sp); err = err(ok); sp = sp(ok); n = numel(err);
    h = std(err) / mean(sp);
    th = zeros(n, 1);
    for i = 1:n; e = err; s = sp; e(i) = []; s(i) = []; th(i) = std(e) / mean(s); end
    se = sqrt((n - 1) / n * sum((th - mean(th)).^2));
end

function [d, se] = local_ratio_diff_jack(ea, sa, eb, sb)
    ok = isfinite(ea) & isfinite(sa) & isfinite(eb) & isfinite(sb);
    ea = ea(ok); sa = sa(ok); eb = eb(ok); sb = sb(ok); n = numel(ea);
    d = std(ea) / mean(sa) - std(eb) / mean(sb);
    th = zeros(n, 1);
    for i = 1:n
        k = true(n, 1); k(i) = false;
        th(i) = std(ea(k)) / mean(sa(k)) - std(eb(k)) / mean(sb(k));
    end
    se = sqrt((n - 1) / n * sum((th - mean(th)).^2));
end

function s = local_branch(mu)
    if mu > 0
        s = 'H3 POSITIVE -- rule change interacts with the y1 correction path; single-factor assumption fails; STOP (hand to residual-1c)';
    elseif mu >= -12 && mu <= -6
        s = 'H1 band (-9 +- 3 pp): quadrature load-bearing as measured (second clause B2 vs B1 below)';
    elseif abs(mu) < 4
        s = 'H2 small (|diff| < 4 pp): closed-loop response differs from the replay';
    elseif abs(mu) > 15
        s = 'H2 large (|diff| > 15 pp): closed-loop response differs from the replay';
    else
        s = 'between registered bands (-6,-4) or (-15,-12): reported as-is, no registered branch';
    end
end

function s = local_cnt(n)
    s = sprintf('%d/%d/%d', sum(n), sum(n > 0), max(n));
end

function s = local_lt(a, b)
    if a < b; s = '<'; else; s = '>='; end
end

function s = local_yesno(tf)
    if tf; s = 'YES'; else; s = 'NO'; end
end
