%PLOT_5STATE_EXPGAIN  Canonical-run figure for the 5-state exponential-gain
%   controller (z axis, wall-normal).
%
%   ONE seed, RAW per-step traces, no averaging and no smoothing: every panel
%   is what this single run actually did. Seed-to-seed scatter belongs in the
%   regression tables, not here.
%
%   Scenario: hold 0.5 s @ h_bar = 22.2 -> descend 1.0 s -> 1 Hz oscillation
%   down to h_bar = 2.0, 2 cycles, T = 4.8 s, thermal + measurement noise ON.
%   Grey dashed verticals mark the hold -> descend -> oscillate boundaries.
%
%   Rows:
%     1  a_z [nm/pN]   true / estimate / raw gain readout a_hm -- is the estimate
%                      tracking the wall, or just copying its own measurement?
%     2  a_z error     (a_hat-a_true)/a_true [%] -- bias and, more importantly,
%                      whether it drifts rather than settling
%     3  b_z           raw per-step estimate against b_slope(h_bar), the
%                      exponent that reproduces the TRUE SLOPE at that height.
%                      NOT against b = 1: that is the modelling assumption, not
%                      the truth, and comparing to it turns correct tracking
%                      into apparent divergence. The gap in this panel IS the
%                      slope error, since a'_model/a'_true = b_hat/b_slope.
%
%   Self-contained: runs the simulation itself so the figure can be regenerated
%   from this one file.

clear; clc;
here = fileparts(mfilename('fullpath'));
proj = fullfile(here, '..', '..');
addpath(genpath(proj));

% 'diff' = a_h is a state swept by a'  (states [a_h, b])  -> the formulation
%          the committed derivation 5state_expgain_hd.tex describes
% 'alg'  = a_h evaluated from the model (states [a_o, b], both constant)
% The output filename ALWAYS carries the variant, so the .tex reference cannot
% silently start pointing at a figure generated by a different model.
VARIANT = 'diff';

cfg = user_config();
cfg.trajectory_type = 'osc';
cfg.h_init   = 50;
cfg.h_bottom = 4.5;
cfg.amplitude = 2.5;
cfg.frequency = 1;
cfg.n_cycles  = 2;
cfg.t_hold    = 0.5;
cfg.t_descend_override = 1.0;
cfg.T_sim     = 4.8;
pc = physical_constants();
cfg.h_min     = 1.05 * pc.R;
cfg.ctrl_enable = true;
cfg.thermal_enable    = true;
cfg.meas_noise_enable = true;
cfg.lambda_c = 0.7;
cfg.a_pd  = 0.05;
cfg.a_cov = 0.05;
cfg.meas_noise_std = [0.00062; 0.00057; 0.00331];
cfg.h_bar_safe = 1.5;
seed = 7;

sim = run_5state_expgain(cfg, struct('seed', seed, 'verbose', false, 'variant', VARIANT));

az  = 3;
t   = sim.tout(:);
a_o = sim.a_nom;
hb  = sim.h_bar_true_out(:);
aT  = sim.a_true_out(:, az);
aH  = sim.a_hat_out(:, az);
aM  = sim.a_xm_out(:, az);
apT = sim.a_prime_true_out(:, az);
apH = sim.a_prime_out(:, az);
bH  = sim.b_hat_out(:, az);
sb  = sim.P_b_out(:, az);
errz = 100 * (aH - aT) ./ aT;

% Reference for b_hat. Each formulation is judged against the reading it
% actually uses, otherwise correct tracking looks like divergence:
%   'diff'  b sets the SLOPE (the level is carried by the a_h state)
%             b_slope = h_bar * a'_true / (a_o - a_true)
%   'alg'   b sets the LEVEL directly
%             b_level = -ln(1 - a_true/a_o) / ln(h_bar)
%           and, since b is then a genuine global constant, the best CONSTANT
%           b over the traversed range is where it should actually settle.
if strcmpi(VARIANT, 'alg')
    bSlope  = -log(max(1 - aT/a_o, eps)) ./ log(max(hb, 1 + 1e-9));
    bRefNm  = 'b_{level} true';
    B_CONST = 0.9386;          % best constant b, h_bar in [2, 22.2]
else
    bSlope  = hb .* apT ./ max(a_o - aT, eps);
    bRefNm  = 'b_{slope} true';
    B_CONST = [];
end

FS = 18;
r = 'r'; b = 'b'; grey = [0.6 0.6 0.6];
tb = [cfg.t_hold, cfg.t_hold + cfg.t_descend_override];
nm = 1e3;

fig = figure('Color', 'w', 'Position', [60 60 900 980]);

% (1) a_z : true / estimate / raw readout, in physical units
ax2 = subplot(3,1,1); hold(ax2, 'on');
hx = plot(ax2, t, aM*nm, 'Color', grey, 'LineWidth', 0.5);
ht = plot(ax2, t, aT*nm, r, 'LineWidth', 2.6);
he = plot(ax2, t, aH*nm, b, 'LineWidth', 2.0);
ylabel(ax2, 'a_z  [nm/pN]', 'FontSize', FS, 'FontWeight', 'bold');
legend([ht he hx], {'a_{true}', 'a_{hat}', 'a_{hm} (raw readout)'}, ...
       'Location', 'northoutside', 'Orientation', 'horizontal', 'FontSize', FS-4);
ylim(ax2, [0 24]); style_ax(ax2, FS); xlim(ax2, [t(1) t(end)]); add_phase(ax2, tb);

% (2) a_z relative error
ax3 = subplot(3,1,2); hold(ax3, 'on');
h0  = plot(ax3, t, zeros(size(t)), r, 'LineWidth', 2.0);
he3 = plot(ax3, t, errz, b, 'LineWidth', 2.0);
plot(ax3, t,  2*ones(size(t)), 'k--', 'LineWidth', 1.2, 'HandleVisibility', 'off');
plot(ax3, t, -2*ones(size(t)), 'k--', 'LineWidth', 1.2, 'HandleVisibility', 'off');
ylabel(ax3, 'a_z error  [%]', 'FontSize', FS, 'FontWeight', 'bold');
legend([h0 he3], {'zero', '(a_{hat}-a_{true})/a_{true}'}, ...
       'Location', 'northoutside', 'Orientation', 'horizontal', 'FontSize', FS-4);
ylim(ax3, [-8 8]); style_ax(ax3, FS); xlim(ax3, [t(1) t(end)]); add_phase(ax3, tb);

% (3) b_z : raw per-step estimate vs b_slope
%     No confidence band: the a' error is exactly b_hat/b_slope - 1, so this
%     panel already carries what a dedicated a' panel would show. The claimed
%     sigma is printed to the console instead of shaded here.
ax5 = subplot(3,1,3); hold(ax5, 'on');
hbt = plot(ax5, t, bSlope, r, 'LineWidth', 2.6);
hbh = plot(ax5, t, bH, b, 'LineWidth', 1.6);
h1  = plot(ax5, t, ones(size(t)), 'k--', 'LineWidth', 1.2);
hnd = [hbt hbh h1];  lbl = {bRefNm, 'b_{hat} raw', 'b = 1 (both anchors)'};
if ~isempty(B_CONST)
    hbc = plot(ax5, t, B_CONST*ones(size(t)), 'Color', [0 0.5 0], 'LineWidth', 1.6);
    hao = plot(ax5, t, sim.ao_hat_out(:, az)/a_o, 'Color', [0.85 0.4 0], 'LineWidth', 1.4);
    hnd = [hnd hbc hao];
    lbl = [lbl, {'best const b', 'a_{o,hat}/a_{nom}'}];
end
ylabel(ax5, 'b_z  (raw)', 'FontSize', FS, 'FontWeight', 'bold');
xlabel(ax5, 'time  [s]', 'FontSize', FS, 'FontWeight', 'bold');
legend(hnd, lbl, 'Location', 'northoutside', 'Orientation', 'horizontal', ...
       'FontSize', FS-6);
ylim(ax5, [0.85 1.20]); style_ax(ax5, FS); xlim(ax5, [t(1) t(end)]); add_phase(ax5, tb);

fig_dir = fullfile(proj, 'reference', 'eq17_analysis', 'derivation', 'figures');
if ~exist(fig_dir, 'dir'); mkdir(fig_dir); end
outp = fullfile(fig_dir, sprintf('expgain_5state_sim_%s.png', lower(VARIANT)));
exportgraphics(fig, outp, 'Resolution', 150);
close(fig);

osc = t > 1.6;
fprintf('FIGURE saved: %s\n', outp);
fprintf('seed %d, h_bar range [%.2f, %.2f]\n', seed, min(hb), max(hb));
fprintf('a_z  error : osc-window mean %+.2f %%, max|err| %.2f %%\n', ...
        mean(errz(osc)), max(abs(errz(osc))));
fprintf('a''_z error : osc-window RMS %.2f %%, max %.2f %%  (single-b truncation\n', ...
        100*sqrt(mean(((apH(osc)-apT(osc))./apT(osc)).^2)), ...
        100*max(abs((apH(osc)-apT(osc))./apT(osc))));
fprintf('             against the exact curve is 2.50 %% RMS over h_bar in [2,22])\n');
fprintf('b_z  raw   : mean %.4f, std %.4f, range [%.4f %.4f]\n', ...
        mean(bH(osc)), std(bH(osc)), min(bH), max(bH));
fprintf('b_slope    : range [%.4f %.4f], osc-window mean %.4f\n', ...
        min(bSlope(2:end)), max(bSlope(2:end)), mean(bSlope(osc)));
fprintf('b_hat - b_slope : osc mean %+.4f, max|err| %.4f, claimed sigma %.4f -> %.4f\n', ...
        mean(bH(osc)-bSlope(osc)), max(abs(bH(osc)-bSlope(osc))), sb(1), sb(end));


function style_ax(ax, FS)
    set(ax, 'FontSize', FS-2, 'FontWeight', 'bold', 'LineWidth', 1.3, 'Box', 'on');
    grid(ax, 'off');
end

function add_phase(ax, tb)
    yl = ylim(ax);
    for x = tb
        plot(ax, [x x], yl, '--', 'Color', [0.55 0.55 0.55], 'LineWidth', 1.0, ...
             'HandleVisibility', 'off');
    end
    ylim(ax, yl);
end
